language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker build -t danshan/webhook-slack .

script:
  - mvn test -B
after_success:
  - mvn clean test #jacoco:report coveralls:report
  - mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
