language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker build -t danshan/webhook-slack .

script:
  - mvn test -B

notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5